spring:
  cloud:
    gateway:
      routes:
        # USUARIOS
        - id: usuarios-service
          uri: http://servicio-usuarios:8081
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=1

        # INVENTARIO
        - id: inventario-service
          uri: http://servicio-inventario:8083
          predicates:
            - Path=/api/inventario/**
          filters:
            - StripPrefix=1

        # VENTAS
        - id: ventas-service
          uri: http://servicio-ventas:8082
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=1
